@startuml
class A {
    +{abstract} ~A() : void
    +a : int
}

class B {
    +b : int
}

class C {
    +c : int
}

class D {
    +d : int
}

A <|-- B : virtual
A <|-- C : virtual
B <|-- D
C <|-- D
@enduml